///////////////////////////////////////////////////////////
//  ControlOperation.cs
//  Implementation of the Class ControlOperation
//  Generated by Enterprise Architect
//  Created on:      23-Jan-2007 21:52:03
//  Original author: Marcelo
///////////////////////////////////////////////////////////




using Iris.Runtime.Model;
using Iris.Runtime.Model.BaseObjects;
using System;
namespace Iris.Runtime.Model.Operations.Control
{
  [Serializable]
  public abstract class ControlOperation : Operation
  {

    public ControlOperation(Structure aStructure,string aName)
      : base(aStructure, aName)
    {

    }

  }//end ControlOperation

}//end namespace ControlOperations