///////////////////////////////////////////////////////////
//  FromMember.cs
//  Implementation of the Class FromMember
//  Generated by Enterprise Architect
//  Created on:      04-Jan-2007 21:41:42
//  Original author: Marcelo
///////////////////////////////////////////////////////////


using System;
namespace Iris.Runtime.Core.ParserObjects
{
  [Serializable]
  public abstract class FromMember : BaseParserObject
  {

    public FromMember()
    {

    }


    private string alias;

    public virtual string Alias
    {
      get { return alias; }
      set { alias = value; }
    }

    private bool crossJoin;

    public bool CrossJoin
    {
      get { return crossJoin; }
      set { crossJoin = value; }
    }
  }//end FromMember

}//end namespace Parser