///////////////////////////////////////////////////////////
//  IdList.cs
//  Implementation of the Class IdList
//  Generated by Enterprise Architect
//  Created on:      04-Jan-2007 21:41:42
//  Original author: Marcelo
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using System;
namespace Iris.Runtime.Core.ParserObjects
{
  [Serializable]
  public class FromTable : FromMember
  {

    public FromTable(string aTableName, string aAlias)
    {
      TableName = aTableName;
      Alias = aAlias;
    }

    private string tableName;

    public string TableName
    {
      get { return tableName; }
      set { tableName = value; }
    }

    public override string Alias
    {
      get
      {
        if (string.IsNullOrEmpty(base.Alias))
          return TableName;
        else
          return base.Alias;
      }
      set
      {
        base.Alias = value;
      }
    }

    public override string GetText()
    {
      if (Alias != TableName)
        return TableName + " AS " + Alias;
      else
        return TableName;
    }
  }//end IdList

}//end namespace Parser