///////////////////////////////////////////////////////////
//  JoinType.cs
//  Implementation of the Class JoinType
//  Generated by Enterprise Architect
//  Created on:      04-Jan-2007 21:41:42
//  Original author: Marcelo
///////////////////////////////////////////////////////////




namespace Parser.ParserObjects
{
  public enum JoinType : int
  {

    None,
    Inner,
    LeftOuter,
    RightOuter

  }//end JoinType

}//end namespace Parser