///////////////////////////////////////////////////////////
//  SubQuery.cs
//  Implementation of the Class SubQuery
//  Generated by Enterprise Architect
//  Created on:      04-Jan-2007 21:41:43
//  Original author: Marcelo
///////////////////////////////////////////////////////////




using System;
namespace Iris.Runtime.Core.ParserObjects
{
  [Serializable]
  public class SubQuery : FromMember
  {
    public SubQuery(string aAlias)
    {
      Alias = aAlias;
    }

    private SelectQuery query;

    public SelectQuery Query
    {
      get { return query; }
      set { query = value; }
    }

    public override string GetText()
    {
      return "(" + query.GetText() + ") AS " + Alias;
    }
  }//end SubQuery

}//end namespace Parser